import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium, expect } from '@playwright/test';
import { createApp } from '../dist/app.js';

const directory = await mkdtemp(join(tmpdir(), 'observatory-ui-'));
const p = 'langfuse.observation.';
const filename = '2026-09-27-15-59-36-ses_browser.jsonl';
const records = [
  { [p + 'type']: 'event', [p + 'input']: [{ role: 'user', content: 'Search for a test result' }], startTimeUnixNano: '1790495971615000000' },
  { [p + 'type']: 'tool', [p + 'metadata']: { callID: 'call_browser', tool: 'websearch' }, [p + 'input']: { query: 'test' }, [p + 'output']: { output: 'Matched tool result' }, startTimeUnixNano: '1790496018942000000' },
  { [p + 'type']: 'generation', [p + 'model.name']: 'test-model', [p + 'metadata']: { providerID: 'test-provider', variant: 'medium', mode: 'build' }, [p + 'input']: { system: ['private system history'], messages: [{ role: 'user', content: 'Search' }] }, [p + 'output']: [{ role: 'assistant', thinking: [{ type: 'thinking', content: 'Looking it up' }], tool_calls: [{ id: 'call_browser', name: 'websearch', arguments: '{"query":"test"}' }] }], [p + 'usage_details']: { input: 100, output: 20, reasoning: 10, cache_read: 900, cache_write: 0, total: 130 }, [p + 'cost_details']: { total: 0 }, startTimeUnixNano: '1790496016931000000' },
  { [p + 'type']: 'generation', [p + 'input']: { messages: [{ role: 'user' }, { role: 'assistant' }, { role: 'tool' }] }, [p + 'output']: [{ role: 'assistant', content: '**Final answer**\n\n<script>window.untrustedExecuted=true</script>\n\n[Unsafe](javascript:alert(1))' }], [p + 'usage_details']: { input: 50, output: 30, reasoning: 0, cache_read: 950, cache_write: 0, total: 80 }, [p + 'cost_details']: { total: 0 }, startTimeUnixNano: '1790496026931000000' },
];
const serialize = values => values.map(value => JSON.stringify(value)).join('\n') + '\n';
let browser;
const app = createApp(() => {}, directory);
try {
  await writeFile(join(directory, filename), serialize(records));
  const address = await app.listen({ host: '127.0.0.1', port: 0 });
  browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || (process.platform === 'win32' ? 'msedge' : undefined) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [];
  const historyRequests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().includes('&item=')) historyRequests.push(request.url()); });
  await page.goto(`${address}/dashboard`);
  await expect(page.locator('.session-link')).toHaveCount(1);
  await page.getByRole('textbox', { name: 'Search sessions' }).fill('absent');
  await expect(page.getByText('No matching sessions')).toBeVisible();
  await page.getByRole('button', { name: 'Clear search' }).click();
  await expect(page.locator('.session-link h3')).toHaveText('Search for a test result');
  await page.locator('.session-link').click();
  await expect(page.locator('h1')).toHaveText('Search for a test result');
  await expect(page.locator('.session-filename')).toHaveText(filename);
  await expect(page).toHaveTitle('Search for a test result · Observatory');
  await expect(page.locator('.session-metrics .metric').last()).toContainText('Total duration');
  await expect(page.locator('.session-metrics .metric').last().locator('strong')).toHaveText('55s');
  await expect(page.locator('.observation')).toHaveCount(3);
  assert.deepEqual(await page.locator('.observation').evaluateAll(nodes => nodes.map(node => node.id)), ['observation-4', 'observation-3', 'observation-1']);
  await expect(page.locator('#observation-4 .type-icons .type-icon.response')).toHaveCount(1);
  await expect(page.locator('#observation-4 .type-icons .type-icon.generation')).toHaveCount(0);
  assert.deepEqual(await page.locator('#observation-3 .type-icons .type-icon').evaluateAll(nodes => nodes.map(node => [...node.classList].at(-1))), ['generation', 'tool']);
  await expect(page.locator('.is-open')).toHaveCount(1);
  await expect(page.locator('.is-open')).toHaveAttribute('id', 'observation-4');
  assert.equal(await page.locator('.observation').first().getAttribute('id'), await page.locator('.is-open').getAttribute('id'));
  const topBorders = () => page.locator('.observation').evaluateAll(nodes => nodes.map(node => getComputedStyle(node).borderTopWidth));
  assert.deepEqual(await topBorders(), ['1px', '1px', '0px']);
  await expect(page.locator('.raw-history[open]')).toHaveCount(0);
  assert.equal(historyRequests.length, 0);
  await expect(page.locator('.is-open .prose strong')).toHaveText('Final answer');
  assert.equal(await page.evaluate(() => window.untrustedExecuted), undefined);
  assert.equal(await page.locator('a[href^="javascript:"]').count(), 0);
  const answer = page.locator('#observation-4 .output .text-content');
  await answer.getByRole('button', { name: 'Raw' }).click();
  await expect(answer.locator('pre code')).toContainText('**Final answer**');
  await expect(answer.locator('pre code')).toContainText('<script>window.untrustedExecuted=true</script>');
  await expect(answer.locator('.prose')).toHaveCount(0);
  assert.equal(await page.evaluate(() => window.untrustedExecuted), undefined);
  await answer.getByRole('button', { name: 'Markdown' }).click();
  await expect(answer.locator('.prose strong')).toHaveText('Final answer');

  await page.locator('#observation-3 .observation-summary').click();
  assert.deepEqual(await topBorders(), ['1px', '1px', '1px']);
  await expect(page.locator('#observation-3 .tool-results')).toContainText('Matched tool result');
  const toolText = page.locator('#observation-3 .tool-result .text-content');
  await toolText.getByRole('button', { name: 'Raw' }).click();
  await expect(toolText.locator('pre code')).toHaveText('Matched tool result');
  await expect(answer.getByRole('button', { name: 'Markdown' })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('#observation-3')).toContainText('90.0%');
  await page.locator('#observation-3 .raw-history summary').click();
  await expect(page.locator('#observation-3 .raw-history pre')).toContainText('private system history');
  assert.equal(historyRequests.length, 1);
  await page.getByRole('button', { name: 'Collapse all', exact: true }).click();
  await expect(page.locator('.is-open')).toHaveCount(0);
  assert.deepEqual(await topBorders(), ['1px', '0px', '0px']);
  await page.locator('.chart-column').first().click();
  await expect(page.locator('#observation-3')).toHaveClass(/is-open/);
  await page.getByRole('button', { name: 'User', exact: true }).click();
  await expect(page.locator('.observation')).toHaveCount(1);
  await page.getByRole('button', { name: 'Jump to latest', exact: true }).click();
  await expect(page.locator('.observation')).toHaveCount(3);
  await expect(page.locator('#observation-4')).toHaveClass(/is-open/);

  records.push({ [p + 'type']: 'event', [p + 'input']: [{ role: 'user', content: 'New live message' }], startTimeUnixNano: '1790496036931000000' });
  await writeFile(join(directory, filename), serialize(records));
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.locator('.observation')).toHaveCount(4);
  assert.deepEqual(await page.locator('.observation').evaluateAll(nodes => nodes.map(node => node.id)), ['observation-5', 'observation-4', 'observation-3', 'observation-1']);
  await expect(page.locator('.is-open')).toHaveCount(1);
  await expect(page.locator('#observation-5')).toHaveClass(/is-open/);
  await page.getByRole('textbox', { name: 'Search observations' }).fill('no match');
  await expect(page.getByRole('heading', { name: 'No observations found' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Expand all', exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await expect(page.locator('.is-open')).toHaveCount(4);
  const longTitle = 'A long first request that needs to be shortened in the session heading '.repeat(3).trim();
  records[0][p + 'input'][0].content = longTitle;
  await writeFile(join(directory, filename), serialize(records));
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.locator('.session-title')).toHaveText(longTitle);
  await expect(page.locator('.session-title')).toHaveAttribute('title', longTitle);
  assert.equal(await page.locator('.session-title').evaluate(node => node.scrollHeight > node.clientHeight), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.evaluate(() => window.scrollTo(0, 0));
  await expect(page.locator('.floating-actions')).toBeHidden();
  await page.evaluate(() => window.scrollTo(0, 800));
  const shortcuts = page.getByRole('navigation', { name: 'Session shortcuts' });
  await expect(shortcuts).toBeVisible();
  await expect(shortcuts.getByRole('link', { name: 'All sessions' })).toHaveAttribute('href', '/dashboard');
  await shortcuts.getByRole('checkbox', { name: 'Auto-refresh' }).check();
  await expect(page.locator('.workspace-toolbar').getByRole('checkbox', { name: 'Auto-refresh' })).toBeChecked();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
  await expect(page.locator('.floating-actions')).toBeHidden();
  await page.evaluate(() => window.scrollTo(0, 800));
  await expect(shortcuts).toBeVisible();
  await shortcuts.getByRole('button', { name: 'Back to top' }).click();
  await expect(page.locator('.floating-actions')).toBeHidden();
  assert.equal(await page.evaluate(() => scrollY), 0);
  await page.goto(`${address}/dashboard?session=missing.jsonl`);
  await expect(page.getByRole('alert')).toContainText('Session not found');
  await page.getByRole('link', { name: 'Back to library' }).click();
  await expect(page.locator('.session-link')).toHaveCount(1);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: library search, navigation, newest-first timeline, expansion, tool matching, lazy history, chart navigation, filtering, refresh, Markdown safety, mobile layout, and error recovery.');
} finally {
  await browser?.close();
  await app.close();
  await rm(directory, { recursive: true, force: true });
}
